# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'VKontakte' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for VKontakte
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'Kingfisher', '~> 5.11.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Realm', '~> 4.2.0'
  pod 'RealmSwift', '~> 4.2.0'
  
end
